### ISSUE TITLE
Loop on mail error

### ISSUE THREAD

**Issue by elpoleto** [squareboat/sneaker#31]
Hello. i use MS Azure as smtp and when some errors occour the sneaker jump in a infinite loop of errors tring to sends mails, for example:

> Expected response code 250 but got code "432", with message "432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=DB6PR0901MB0790.eurprd09.prod.outlook.com]^M
> " {"exception":"[object] (Swift_TransportException(code: 432): Expected response code 250 but got code \"432\", with message \"432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded ..... 

or 

> Expected response code 250 but got code "554", with message "554 5.2.0 STOREDRV.Submission.Exception:SubmissionQuotaExceededException; Failed to process message due to a permanent exception with message The message can't be submitted because the sender's submission quota was exceeded. SubmissionQuotaExceededException: The message can't be submitted because the sender's submission quota was exceeded.

my config capture is 
`'capture' => [
        Symfony\Component\Debug\Exception\FatalErrorException::class,
    ],`

but it goes in infinite loop

Any way to avoid that please?

**Comment by elpoleto** [comment]
if can help

> #0 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('554 5.2.0 STORE...', Array)
#1 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('\r\n.\r\n', Array, Array, false, NULL)
#2 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(404): Swift_Transport_EsmtpTransport->executeCommand('\r\n.\r\n', Array)
#3 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(500): Swift_Transport_AbstractSmtpTransport->streamMessage(Object(Swift_Message))
#4 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'noreply@coges.e...', Array, Array)
#5 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'noreply@coges.e...', Array, Array)
#6 /var/www/wsapi/releases/20190128144955/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(464): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(248): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(148): Illuminate\Mail\Mailer->send('sneaker::raw', Array, Object(Closure))
#10 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(18): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#11 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(149): Illuminate\Mail\Mailable->withLocale(NULL, Object(Illuminate\Translation\Translator), Object(Closure))
#12 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(52): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer))
#13 [internal function]: Illuminate\Mail\SendQueuedMailable->handle(Object(Illuminate\Mail\Mailer))
#14 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#19 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#20 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Mail\SendQueuedMailable))
#21 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Mail\SendQueuedMailable), false)
#23 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#24 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#25 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(37): Illuminate\Queue\SyncQueue->push(Object(Illuminate\Mail\SendQueuedMailable), '', NULL)
#26 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(169): Illuminate\Queue\Queue->pushOn(NULL, Object(Illuminate\Mail\SendQueuedMailable))
#27 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(370): Illuminate\Mail\Mailable->queue(Object(Illuminate\Queue\QueueManager))
#28 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(147): Illuminate\Mail\Mailer->queue(Object(SquareBoat\Sneaker\ExceptionMailer))
#29 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(116): Illuminate\Mail\PendingMail->queue(Object(SquareBoat\Sneaker\ExceptionMailer))
#30 /var/www/wsapi/releases/20190128144955/vendor/squareboat/sneaker/src/Sneaker.php(111): Illuminate\Mail\PendingMail->send(Object(SquareBoat\Sneaker\ExceptionMailer))
#31 /var/www/wsapi/releases/20190128144955/vendor/squareboat/sneaker/src/Sneaker.php(81): SquareBoat\Sneaker\Sneaker->capture(Object(SquareBoat\Sneaker\Exceptions\DummyException))
#32 /var/www/wsapi/releases/20190128144955/vendor/squareboat/sneaker/src/Commands/Sneak.php(57): SquareBoat\Sneaker\Sneaker->captureException(Object(SquareBoat\Sneaker\Exceptions\DummyException), true)
#33 [internal function]: SquareBoat\Sneaker\Commands\Sneak->handle()
#34 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array)
#39 /var/www/wsapi/releases/20190128144955/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/wsapi/releases/20190128144955/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/wsapi/releases/20190128144955/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(SquareBoat\Sneaker\Commands\Sneak), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/wsapi/releases/20190128144955/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/wsapi/releases/20190128144955/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/wsapi/releases/20190128144955/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}

**Comment by codegain** [comment]
@elpoleto I will assume that you have queueing enabled, so that the error mails will be pushed onto it and then sent. If that's the case, Sneaker tries the following:

1. Exception is thrown
2. Exception is captured by Sneaker
3. Sneaker generates an error mail and pushes it onto the queue
4. The worker can't send the error mail, because the SMTP server responsed with an error
5. The worker throws an exception
6. Loop to 1.

This should generally be avoided by the code in Sneaker.php:83 where the "try-catch" block catches the exception from Sneaker. But if the mail is sent via the queue, the mailer does not throw an exception.

The only workaround I found is to parse the stack trace of the exception, look for "SquareBoat\Sneaker\ExceptionMailer" and then don't call app('sneaker')->captureException($e).

**Comment by elpoleto** [comment]
Thanks, for now i resolved starting the queue work with 3 tries, so i got only 3 error and the the loop is blocked.
I think is better wrap the Sneaker.php:111 line "$this->mailer->to($recipients)->send(new ExceptionMailer($subject, $body));" with a try except

**Comment by akaamitgupta** [comment]
@elpoleto The `capture()` method of `Sneaker.php` is already wrapped into the try catch block. It's inside the `ExceptionMailer` class where the exception is thrown. So we can wrap that in a try catch block. I will soon implement this.

@codegain We cant remove the "ShouldQueue" interface as we want the mail to be sent using queue only. I don't find any good reason to remove it here. But making it configurable is much more appropriate. So will work on that soon or a PR is also welcomed.
